/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanpraktikumii;

/**
 *
 * @author Iqbal Albana
 */
public class Frame1 extends javax.swing.JFrame {
    String jns = "";
    int jml;
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JLabel();
        b2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JLabel();
        b3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 270, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 90, 30);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(290, 80, 130, 30);

        panel.setBackground(new java.awt.Color(102, 255, 0));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        ket.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        panel.add(ket);
        ket.setBounds(160, 20, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(60, 60, 100, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(190, 60, 150, 30);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(70, 100, 100, 30);
        panel.add(b1);
        b1.setBounds(190, 100, 150, 30);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(70, 140, 100, 30);
        panel.add(b2);
        b2.setBounds(190, 140, 150, 30);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(70, 180, 100, 30);
        panel.add(b3);
        b3.setBounds(190, 180, 150, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(70, 220, 100, 30);
        panel.add(b4);
        b4.setBounds(190, 220, 150, 30);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(160, 260, 90, 30);
        panel.add(thasil);
        thasil.setBounds(20, 300, 350, 80);

        getContentPane().add(panel);
        panel.setBounds(40, 120, 390, 410);

        setBounds(0, 0, 496, 589);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                thasil.setText(""+ a1 + "+" + a2 + "=" + hsl);
            }
            if(jml == 3){
                hsl = a1 + a2 + a3;
                thasil.setText(""+ a1 + "+" + a2 + "+" + a3 + "="  + hsl);
            }
            if(jml == 4){
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+ a1 + "+" + a2 + "+" + a3 + "+" + a4 + "="  + hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                thasil.setText(""+ a1 + "-" + a2 + "=" + hsl);
            }
            if(jml == 3){
                hsl = a1 - a2 - a3;
                thasil.setText(""+ a1 + "-" + a2 + "-" + a3 + "="  + hsl);
            }
            if(jml == 4){
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+ a1 + "-" + a2 + "-" + a3 + "-" + a4 + "="  + hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                thasil.setText(""+ a1 + "*" + a2 + "=" + hsl);
            }
            if(jml == 3){
                hsl = a1 * a2 * a3;
                thasil.setText(""+ a1 + "*" + a2 + "*" + a3 + "="  + hsl);
            }
            if(jml == 4){
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+ a1 + "*" + a2 + "*" + a3 + "*" + a4 + "="  + hsl);
            }
        }
        if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                thasil.setText(""+ a1 + "/" + a2 + "=" + hsl);
            }
            if(jml == 3){
                hsl = a1 / a2 / a3;
                thasil.setText(""+ a1 + "/" + a2 + "/" + a3 + "="  + hsl);
            }
            if(jml == 4){
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+ a1 + "/" + a2 + "/" + a3 + "/" + a4 + "="  + hsl);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 2;
        } else if(pilihanbil.getSelectedItem().equals("3")){
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        bil3.setVisible(true);
        bil4.setVisible(false);
        b3.setVisible(true);
        b4.setVisible(false);
        jml = 3;
        } else if(pilihanbil.getSelectedItem().equals("4")){
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 4;
        }
        
    }
    
    
    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables
}
